# Generated by Django 4.1.7 on 2023-02-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='address',
            field=models.CharField(max_length=128),
        ),
    ]
