# Generated by Django 4.1.7 on 2023-02-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_menuitem_parent_menuitem_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='children',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='children',
            field=models.ManyToManyField(to='mainapp.menuitem'),
        ),
    ]
